### PR TITLE
Set changeset ID after import

### LINKED ISSUE #4: Update changeset ID sequence during post-import provisioning
Add a post-import provisioning step that updates the changeset ID sequence to reflect imported changeset IDs. 

See https://github.com/openstreetmap/openstreetmap-website/issues/1542

This came about when trying to open a new changeset via the API, which responded with:
```
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "changesets_pkey"
DETAIL:  Key (id)=(1) already exists.
```

### PR DESCRIPTION
**Pull request by flibbertigibbet**
## Overview

Update the last used changeset ID to match the highest found in the imported .osm/.pbf file(s).

Fixes #4.

## Demo

Running the PUT below after newly building the VM returned for me the new changeset ID `78068330`. 

## Testing

 - `./strta/build.sh`
 - `./strta/serve.sh`
 - Set up user account (see `AZAVEA_README.md`)
 - Creating a changeset via API PUT should succeed: `curl -X PUT -d '<osm><changeset><tag k="created_by" v="{username}"/><tag k="comment" v="Testing changeset creation"/></changeset></osm>' http://localhost:3003/api/0.6/changeset/create --user {username}:{password}`

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
Connects azavea/geospatial-apps#235

**Comment by lederer** [comment]
I'm getting this error when attempting to create the first user. I've tried multiple times.

`PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "users_pkey" DETAIL: Key (id)=(1) already exists.`

This is  fresh install into a new directory, as follows:
```
$ git clone https://github.com/azavea/openstreetmap-website.git
$ cd openstreetmap-website
$ git remote add flibbertigibbet https://github.com/flibbertigibbet/openstreetmap-website.git
$ git fetch flibbertigibbet
$ git checkout feature/kak/set-sequence-post-import#4
$ ./strta/build.sh
$ ./strta/serve.sh
🌎 http://localhost:3003/user/new
```

After submitting the new user form and the subsequent license agreement page, I land on this error page:

localhost_3003_user_save

**Comment by flibbertigibbet** [comment]
Thanks for taking a look @lederer. I hadn't run into that issue myself, as I'd re-used my existing user account that was already in the import. There are a number of tables, including those for ways, relations, and nodes, that have sequenced IDs that require update after import.

I've updated the PR to set all sequence IDs that may require it after import.

**Review by lederer — APPROVED** [review]
👍 Works as described. Thanks for making the update!

**Pull request merged**
